sudo: required
services:
  - docker

before_install:
  - docker build -t amsevrid/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run amsevrid/react-test npm test -- --coverage

after_success:
  - docker build -t amsevrid/multi-client ./client
  - docker build -t amsevrid/multi-nginx ./nginx
  - docker build -t amsevrid/multi-server ./server
  - docker build -t amsevrid/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push amsevrid/multi-client
  - docker push amsevrid/multi-nginx
  - docker push amsevrid/multi-server
  - docker push amsevrid/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-east-1-873629052627
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
